package main

import "errors"
import "flag"

type Account struct {
	UUID    int // need to be generated by db?
	Name    string
	Balance int
}

var ErrUUIDConflict = errors.New("UUID already exists")
var ErrAcountBelowZ = errors.New("Account balance below zero")
var ErrAccountNotFound = errors.New("Account not found")

//var Accounts map[int]Account

func Create_account(name string, balance int) Account {
	// check if account exists
	id := Create_account_db(name, balance)
	account := Account{id, name, balance}

	return account
}

func (account *Account) Add_balance(amount int) {
	account.Balance += amount
	account.update()
}

func (account *Account) update() {
	update_account_db(*account)
}

func account_by_uuid(uuid int) (Account, error) {
	account, err := account_by_uuid_db(uuid)
	if err != nil {
		return account, err
	}

	return account, nil
}

func (account *Account) Print() {
	println(account.UUID, account.Name, account.Balance)
}

func (account *Account) Charge(amount int) error {
	if account.Balance-amount < 0 {
		return ErrAcountBelowZ
	}
	account.Balance -= amount
	account.update()
	return nil
}
func Delete_user(uuid int) error {
	err := delete_user_db(uuid)
	return err
}

func Get_all_accounts() []Account {
	return get_all_accounts_db()
}

func main() {
	cli := flag.Bool("cli", false, "start cli runner")
	api := flag.Bool("api", false, "start api server")
	flag.Parse()
	if *api {
		go InitServer()
	}
	if *cli {
		runner()
	}
}
func init() {
	InitDB()
}
