name: Go
on: [push] # all branches

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: postgres
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name : lint gocode
      run : go fmt *.go

    - name : test
      run : go test -v .

    - name: Build # Build bin but don't need yet
      run: go build -v

  postgres:
    runs-on: [ubuntu-latest]
    name: Postgres
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/postgres
