name: Go
on: [push] # all branches
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name : lint gocode
      run : gofmt *.go
      
    - name: Build # Build bin but don't need yet
      run: go build -v 
      
  test:
    name: Run go tests
    needs: build
    runs-on: [ubuntu-latest]
    steps:
      - name: Run tests
        run: go test
    
